#!/usr/bin/env python3
"""Record the test fixtures against the live API.

The fixtures *are* the on-disk response cache. The test suite then runs the
real pipeline with an offline client pointed at that directory, so a missing
fixture surfaces as an error instead of a silent network call.

Run it from a machine with access to Wikimedia hosts, or via the
"Verify assumptions" workflow with mode=fixtures:

    export WP_TODO_CONTACT="https://github.com/metaodi/wp-todo"
    uv run python scripts/record_fixtures.py

It picks a narrow, reproducible slice of the Thalwil tile: articles that carry
a weighted maintenance category (so the acceptance test has something to find),
plus a few that carry none (so the boring edges are covered too). The chosen
titles are written to tests/fixtures/scope.toml, which the tests load.
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from wp_todo.cache import ResponseCache
from wp_todo.client import MAX_LIMIT, WikiClient
from wp_todo.config import MetaConfig, ScopeConfig, load_scope
from wp_todo.fetch import fetch

FIXTURE_DIR = Path("tests/fixtures")
HTTP_DIR = FIXTURE_DIR / "http"
SCOPE_PATH = FIXTURE_DIR / "scope.toml"

# The slice: a small radius around Thalwil, the vertical-slice target.
TILE = {"label": "Thalwil", "lat": 47.2906, "lon": 8.5661, "radius_m": 5000}
INTERESTING = 12
BORING = 4


def pick_titles(client: WikiClient, scope: ScopeConfig) -> tuple[list[str], list[str]]:
    """One geosearch request, split into articles with and without a weighted
    maintenance category."""
    pages = client.query_pages(
        generator="geosearch",
        ggscoord=f"{TILE['lat']}|{TILE['lon']}",
        ggsradius=TILE["radius_m"],
        ggslimit=MAX_LIMIT,
        ggsnamespace=0,
        prop="categories",
        cllimit="max",
    )
    interesting: list[str] = []
    boring: list[str] = []
    for page in sorted(pages.values(), key=lambda p: str(p.get("title", ""))):
        title = str(page.get("title", ""))
        if not title or scope.is_excluded(title) is not None:
            continue
        categories = [str(c["title"]) for c in page.get("categories", []) or [] if "title" in c]
        weighted = [c for c in categories if (scope.scoring.maintenance_weight(c) or ("", 0.0))[1] > 0]
        (interesting if weighted else boring).append(title)
    return interesting[:INTERESTING], boring[:BORING]


def write_scope(titles: list[str], contact: str) -> None:
    quoted = ",\n    ".join(f'"{t}"' for t in titles)
    SCOPE_PATH.write_text(
        "# Recorded slice for the test suite. Generated by scripts/record_fixtures.py.\n"
        "# Titles are explicit so the fixture set stays small and reproducible.\n\n"
        f"pages = [\n    {quoted},\n]\n\n"
        "[meta]\n"
        f'contact = "{contact}"\n'
        'user_agent_product = "wp-todo-tests"\n\n'
        "[exclude]\n"
        "titles = []\n\n"
        "[scoring]\n"
        "history_depth = 25\n\n"
        "[scoring.maintenance]\n"
        '"Kategorie:Wikipedia:Veraltet seit" = 60.0\n'
        '"Kategorie:Wikipedia:Veraltet nach" = 45.0\n'
        '"Kategorie:Wikipedia:Veraltet in" = 15.0\n'
        '"Kategorie:Wikipedia:Veraltet" = 50.0\n'
        '"Kategorie:Wikipedia:Lückenhaft" = 25.0\n'
        '"Kategorie:Wikipedia:Überarbeiten" = 25.0\n'
        '"Kategorie:Wikipedia:Belege fehlen" = 15.0\n'
        '"Kategorie:Wikipedia:Weblink offline IABot" = 1.0\n'
        '"Kategorie:Wikipedia:Weblink offline" = 4.0\n'
        '"Kategorie:Wikipedia:Defekte Weblinks" = 1.0\n\n'
        "[[scoring.markers]]\n"
        'code = "stand_year"\n'
        "pattern = 'Stand:?\\\\s*(?:[A-Za-zä.]+\\\\s+)?(?P<year>(?:19|20)\\\\d{2})'\n"
        "max_age_years = 3\n"
        "weight = 12.0\n\n"
        "[[scoring.markers]]\n"
        'code = "derzeit"\n'
        "pattern = '\\\\b(?:derzeit|zurzeit|aktuell)\\\\b'\n"
        "max_age_years = 5\n"
        "weight = 8.0\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--keep", action="store_true", help="do not clear the existing fixtures first")
    args = parser.parse_args()

    contact = os.environ.get("WP_TODO_CONTACT", "").strip()
    if not contact:
        print("ERROR: set WP_TODO_CONTACT to an email address or project URL", file=sys.stderr)
        return 2

    if HTTP_DIR.exists() and not args.keep:
        shutil.rmtree(HTTP_DIR)
    HTTP_DIR.mkdir(parents=True, exist_ok=True)

    live_scope = load_scope(Path("config/scope.toml"))
    meta = MetaConfig(contact=contact, user_agent_product="wp-todo-tests")

    # Pass one: choose the slice. This request is recorded too, harmlessly.
    with WikiClient(meta=meta, cache=ResponseCache(HTTP_DIR)) as client:
        interesting, boring = pick_titles(client, live_scope)
    titles = sorted(interesting + boring)
    if not interesting:
        print("ERROR: no article in the slice carries a weighted maintenance category", file=sys.stderr)
        return 1
    print(f"slice: {len(interesting)} with maintenance categories, {len(boring)} without")
    write_scope(titles, contact)

    # Pass two: run the real fetch over that slice so every request it makes is
    # recorded.
    scope = load_scope(SCOPE_PATH)
    with WikiClient(meta=meta, cache=ResponseCache(HTTP_DIR)) as client:
        result = fetch(scope, client)
        print(f"recorded {client.stats.requests} requests for {len(result.articles)} articles")

    files = sorted(HTTP_DIR.glob("*.json"))
    print(f"{len(files)} fixture files in {HTTP_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
