#!/usr/bin/env python3
"""Record the test fixtures against the live API.

The fixtures *are* the on-disk response cache. The test suite then runs the
real pipeline with an offline client pointed at that directory, so a missing
fixture surfaces as an error instead of a silent network call.

Run it from a machine with access to Wikimedia hosts, or via the
"Verify assumptions" workflow with mode=fixtures:

    export WP_TODO_CONTACT="https://github.com/metaodi/wp-todo"
    uv run python scripts/record_fixtures.py

It picks a narrow, reproducible slice of the Thalwil tile: articles that carry
a weighted maintenance category (so the acceptance test has something to find),
plus a few that carry none (so the boring edges are covered too). The chosen
titles are written to tests/fixtures/scope.toml, which the tests load.
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from wp_todo.cache import ResponseCache
from wp_todo.client import MAX_LIMIT, WikiClient
from wp_todo.config import MetaConfig, ScopeConfig, load_scope
from wp_todo.fetch import fetch

FIXTURE_DIR = Path("tests/fixtures")
HTTP_DIR = FIXTURE_DIR / "http"
SCOPE_PATH = FIXTURE_DIR / "scope.toml"

# The slice: a small radius around Thalwil, the vertical-slice target.
TILE = {"label": "Thalwil", "lat": 47.2906, "lon": 8.5661, "radius_m": 5000}
INTERESTING = 12
BORING = 4
FIXTURE_HISTORY_DEPTH = 25


def pick_titles(client: WikiClient, scope: ScopeConfig) -> tuple[list[str], list[str]]:
    """One geosearch request, split into articles with and without a weighted
    maintenance category."""
    pages = client.query_pages(
        generator="geosearch",
        ggscoord=f"{TILE['lat']}|{TILE['lon']}",
        ggsradius=TILE["radius_m"],
        ggslimit=MAX_LIMIT,
        ggsnamespace=0,
        prop="categories",
        cllimit="max",
    )
    interesting: list[str] = []
    boring: list[str] = []
    for page in sorted(pages.values(), key=lambda p: str(p.get("title", ""))):
        title = str(page.get("title", ""))
        if not title or scope.is_excluded(title) is not None:
            continue
        categories = [str(c["title"]) for c in page.get("categories", []) or [] if "title" in c]
        weighted = [c for c in categories if (scope.scoring.maintenance_weight(c) or ("", 0.0))[1] > 0]
        (interesting if weighted else boring).append(title)
    return interesting[:INTERESTING], boring[:BORING]


def write_scope(titles: list[str], contact: str, live: ScopeConfig) -> None:
    """Emit the fixture scope from the real one.

    Regex patterns go into TOML *literal* strings (single quotes), which perform
    no escape processing - writing them any other way silently doubles every
    backslash, which is exactly the bug this replaced.
    """
    quoted = ",\n    ".join(f'"{t}"' for t in titles)
    lines = [
        "# Recorded slice for the test suite. Generated by scripts/record_fixtures.py.",
        "# Titles are explicit so the fixture set stays small and reproducible.",
        "",
        f"pages = [\n    {quoted},\n]",
        "",
        "[meta]",
        f'contact = "{contact}"',
        'user_agent_product = "wp-todo-tests"',
        "",
        "[scoring]",
        f"history_depth = {FIXTURE_HISTORY_DEPTH}",
        f"edit_age_weight = {live.scoring.edit_age_weight}",
        f"edit_age_half_life_days = {live.scoring.edit_age_half_life_days}",
        f"substantive_min_bytes = {live.scoring.substantive_min_bytes}",
        f"veraltet_seit_bonus_per_year = {live.scoring.veraltet_seit_bonus_per_year}",
        f"veraltet_seit_bonus_cap = {live.scoring.veraltet_seit_bonus_cap}",
        f"marker_cap = {live.scoring.marker_cap}",
        "",
        "[scoring.maintenance]",
    ]
    for prefix, weight in live.scoring.maintenance.items():
        lines.append(f'"{prefix}" = {weight}')
    for rule in live.scoring.markers:
        if "'" in rule.pattern:  # pragma: no cover - would need escaping
            raise ValueError(f"marker {rule.code} contains a quote; cannot use a TOML literal string")
        lines += [
            "",
            "[[scoring.markers]]",
            f'code = "{rule.code}"',
            f"pattern = '{rule.pattern}'",
            f"max_age_years = {rule.max_age_years}",
            f"weight = {rule.weight}",
            f"requires_year = {str(rule.requires_year).lower()}",
            f"year_window = {rule.year_window}",
        ]
    lines += ["", "[scoring.pageviews]", f"months = {live.scoring.pageviews.months}"]
    SCOPE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--keep", action="store_true", help="do not clear the existing fixtures first")
    parser.add_argument(
        "--offline",
        action="store_true",
        help="regenerate tests/fixtures/scope.toml from the already-recorded cache, making no requests",
    )
    args = parser.parse_args()

    contact = os.environ.get("WP_TODO_CONTACT", "").strip() or (
        "https://github.com/metaodi/wp-todo" if args.offline else ""
    )
    if not contact:
        print("ERROR: set WP_TODO_CONTACT to an email address or project URL", file=sys.stderr)
        return 2

    if HTTP_DIR.exists() and not (args.keep or args.offline):
        shutil.rmtree(HTTP_DIR)
    HTTP_DIR.mkdir(parents=True, exist_ok=True)

    live_scope = load_scope(Path("config/scope.toml"))
    meta = MetaConfig(contact=contact, user_agent_product="wp-todo-tests")

    # Pass one: choose the slice. This request is recorded too, harmlessly.
    with WikiClient(meta=meta, cache=ResponseCache(HTTP_DIR), offline=args.offline) as client:
        interesting, boring = pick_titles(client, live_scope)
    titles = sorted(interesting + boring)
    if not interesting:
        print("ERROR: no article in the slice carries a weighted maintenance category", file=sys.stderr)
        return 1
    print(f"slice: {len(interesting)} with maintenance categories, {len(boring)} without")
    write_scope(titles, contact, live_scope)

    # Pass two: run the real fetch over that slice so every request it makes is
    # recorded.
    scope = load_scope(SCOPE_PATH)
    with WikiClient(meta=meta, cache=ResponseCache(HTTP_DIR), offline=args.offline) as client:
        result = fetch(scope, client)
        print(f"recorded {client.stats.requests} requests for {len(result.articles)} articles")

    files = sorted(HTTP_DIR.glob("*.json"))
    print(f"{len(files)} fixture files in {HTTP_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
